openapi: 3.0.2
info:
  title: Topcoder Groups API
  description: Topcoder Groups API
  version: 1.0.0
paths:
  /groups:
    get:
      parameters:
      - description: Filter by challengeID.
        in: query
        name: challengeID
        schema:
          type: string
        x-filter:
          field: ChallengeID
      - description: Filter by group type.
        in: query
        name: type
        schema:
          type: string
          default: challenge
          enum:
            - challenge
            - regular
          x-filter:
            field: Type
      - description:  Filter by group privacy.
        in: query
        name: privacy
        schema:
          type: string
          default: public
          enum:
            - public
            - private
            - secret
        x-filter:
          field: Privacy
      - $ref: '#/components/parameters/Page'
      - description: |
          Desired number of items per page.
        in: query
        name: limit
        schema:
          type: integer
          default: 30
          maximum: 100
          minimum: 1
      responses:
        '200':
          content:
            'application/json':
              schema:
                items:
                  $ref: '#/components/schemas/Group'
                type: array
          description: Success
      tags:
      - Groups
      summary: List groups.
    post:
      responses:
        '201':
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Group'
          description: Success
      tags:
        - Groups
      requestBody:
        $ref: '#/components/requestBodies/GroupPost'
      summary: Add a group.
  '/groups/{id}':
     get:
      parameters:
      - description: |
          The group ID.
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Group'
          description: Success
      tags:
      - Groups
      summary: Get a group.
     patch:
       parameters:
         - description: The group ID.
           in: path
           name: id
           required: true
           schema:
             type: integer
       responses:
         '200':
           content:
             'application/json':
               schema:
                 $ref: '#/components/schemas/Group'
           description: Success
       tags:
         - Groups
       requestBody:
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/GroupPatch'
         required: true
       summary: Update a group.
  '/groups/{id}/members/{userid}':
    delete:
      parameters:
        - description: The group ID.
          in: path
          name: id
          required: true
          schema:
            type: integer
        - description: The Vanilla User ID.
          in: path
          name: userid
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Success
      tags:
        - Groups
      summary: Remove a user from a group.
  '/groups/{id}/members':
    get:
      parameters:
        - description: The group ID.
          in: path
          name: id
          required: true
          schema:
            type: integer
        - description: |
            Page number. See [Pagination](https://docs.vanillaforums.com/apiv2/#pagination).
          in: query
          name: page
          schema:
            type: integer
            default: 1
            minimum: 1
        - description: Desired number of items per page.
          in: query
          name: limit
          schema:
            type: integer
            default: 30
            maximum: 100
            minimum: 1
      responses:
        '200':
          content:
            'application/json':
              schema:
                items:
                  $ref: '#/components/schemas/GroupMember'
                type: array
          description: Success
      tags:
        - Groups
      summary: The list of group members.
    post:
      parameters:
        - description: The group ID.
          in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Success
      tags:
        - Groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupMemberPost'
        required: true
      summary: Add member to a group.
  '/groups/{id}/archive':
    put:
      parameters:
        - description: The group ID.
          in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Success
      tags:
        - Groups
      requestBody:
        required: false
      summary: Archive a group.
components:
  requestBodies:
    GroupPost:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GroupPost'
      required: true
    GroupPatch:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GroupPatch'
      required: true
  schemas:
    Group:
      properties:
        groupID:
          description: The groupID of the group.
          type: integer
        challengeID:
          description: The challengeID of the Topcoder challenge.
          nullable: true
          type: integer
        challengeUrl:
          description: The url of the Topcoder challenge.
          minLength: 1
          type: string
        name:
          description: The name of the group.
          minLength: 1
          type: string
        privacy:
          description: The privacy of this group
          minLength: 1
          enum:
            - public
            - private
            - secret
        type:
          description: The type of this group
          minLength: 1
          enum:
          - challenge
          - regular
      required:
      - groupID
      - privacy
      - type
      - name
      - challengeID
      - challengeUrl
      type: object
    GroupPost:
      properties:
        name:
          description: The name of the group.
          minLength: 1
          type: string
        privacy:
          type: string
          description: The privacy of the group
          minLength: 1
          enum:
          - public
          - private
          - secret
        type:
          description: The type of this group
          minLength: 1
          enum:
            - challenge
            - regular
        description:
          description: The description of the group.
          minLength: 1
          type: string
        challengeID:
          description: The ID of the Topcoder challenge.
          type: string
        challengeUrl:
          description: The url of the Topcoder challenge.
          type: string
      required:
        - name
        - type
        - privacy
        - description
        - challengeID
        - challengeUrl
      type: object
    GroupPatch:
      properties:
        name:
          description: The name of the group.
          minLength: 1
          type: string
      required:
        - name
      type: object
    GroupMemberPost:
      description: Add a member to a group
      properties:
        userID:
          description: The Vanilla user ID
          type: integer
        watch:
          description: Watch all group categories
          type: boolean
        follow:
          description: Follow all group categories
          type: boolean
      required:
        - userID
      type: object
    GroupMember:
      properties:
        userID:
          description: The userID of an user.
          type: integer
        name:
          description: The name of an user.
          type: name
      required:
        - userID
        - name
      type: object